---
# Wait for Talos API after config apply/reboot

- name: Wait for control plane node API to go down
  ansible.builtin.wait_for:
    host: "{{ talos_ip }}"
    port: 50000
    state: stopped
    timeout: 600
  delegate_to: localhost
  when:
    - not talos_apply_dry_run | bool
    - inventory_hostname in groups['talos_controlplane']
  tags: [apply-config, wait]

- name: Wait for control plane node API to come back up
  ansible.builtin.wait_for:
    host: "{{ talos_ip }}"
    port: 50000
    state: started
    timeout: 900
    delay: 15
  delegate_to: localhost
  when:
    - not talos_apply_dry_run | bool
    - inventory_hostname in groups['talos_controlplane']
  tags: [apply-config, wait]

- name: Wait for worker Talos API to be reachable after reboot
  ansible.builtin.wait_for:
    host: "{{ talos_ip }}"
    port: 50000
    state: started
    timeout: 900
    delay: 15
  delegate_to: localhost
  when:
    - not talos_apply_dry_run | bool
    - inventory_hostname not in groups['talos_controlplane']
  tags: [apply-config, wait]

- name: Wait for control plane API final check
  ansible.builtin.wait_for:
    host: "{{ talos_ip }}"
    port: 50000
    state: started
    timeout: 600
    delay: 15
  delegate_to: localhost
  when:
    - not talos_apply_dry_run | bool
    - inventory_hostname in groups['talos_controlplane']
  tags: [apply-config, wait]
